version: 2

sphinx:
  configuration: docs/source/conf.py

formats:
  - epub
  - pdf

python:
  version: 3.7
  install:
    - method: pip
      path: .
      extra_requirements:
        - rtd
  system_packages: true
