name: ci

on:
  - push
jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version:
          - 3.6
          - 3.7
          - 3.8
    steps:
      - uses: actions/checkout@v2
      - name: Setup Python
        uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python-version }}
      - name: Install
        run: |
          pip install tox
      - name: Linting
        run: tox -e lint
      - name: Run Tests
        run: tox -e py
      - name: Pypi Publish
        run: flit publish
        if: github.ref == 'master'
        env:
          FLIT_USERNAME: ${{ secrets.PYPI_USER }}
          FLIT_PASSWORD: ${{ secrets.PYPI_PASS }}
